name: dharura_barabarani
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  pin_code_fields: ^8.0.1
  awesome_dialog: ^3.1.0
  firebase_app_check: ^0.2.1+8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - images/



  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf

